# This is a basic workflow to help you get started with Actions

name: Setup GHDL environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt-get update
          sudo apt-get install ghdl
          git clone https://github.com/UVVM/UVVM_Light.git uvvm_light
          cd uvvm_light
          mkdir build
          export GHDL_FLAGS="--std=08 -frelaxed --workdir=build --work=uvvm_util"
          ghdl -a $GHDL_FLAGS src_util/types_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/adaptations_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/string_methods_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/protected_types_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/global_signals_and_shared_variables_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/hierarchy_linked_list_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/alert_hierarchy_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/license_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/methods_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/bfm_common_pkg.vhd
          ghdl -a $GHDL_FLAGS src_util/uvvm_util_context.vhd
          ghdl -a $GHDL_FLAGS src_bfm/avalon_mm_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/avalon_st_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/axilite_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/axistream_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/gmii_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/gpio_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/i2c_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/rgmii_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/sbi_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/spi_bfm_pkg.vhd
          ghdl -a $GHDL_FLAGS src_bfm/uart_bfm_pkg.vhd
          echo Add other actions to build,
          echo test, and deploy your project.
