# This is a basic workflow to help you get started with Actions

name: Setup GHDL environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-10 gnat-10 make zlib1g-dev
          git clone https://github.com/ghdl/ghdl.git
          mkdir ghdl/build
          cd ghdl/build
          export CC=/usr/bin/gcc-10
          ../configure
          make
          sudo make install
          cd $GITHUB_WORKSPACE
          git clone https://github.com/UVVM/UVVM_Light.git uvvm_light
          mkdir uvvm_light/build
          cd uvvm_light/build
          . $GITHUB_WORKSPACE/uvvm_light/script/compile.sh ..
          echo Add other actions to build,
          echo test, and deploy your project.
